#!/bin/csh -f

#
# Configuration
#
source mpconfig

#
# Start the executable.
#
exec ./mp.top -I . -I ../../theories/tptp -I ../../theories/czf -I ../../theories/itt -I ../../theories/base -I ../../theories/ocaml -I ../../theories/tactic -I $CAMLP4LIB $*
