#!/bin/sh
cd "`dirname $0`"
. ./mpconfig
if [ "x$MPFONT" = "x" ]; then
    MPFONT="-misc-fixed-medium-r-normal--15-140-75-75-c-90-iso10646-1"
fi
if [ "x$MPBOLD" = "x" ]; then
    MPBOLD=brown
fi
xterm -fn $MPFONT -fb $MPFONT +bdc -xrm "*VT100.colorBD: $MPBOLD" -sb -sl 1000 -e ./mpopt -cli
