#!/bin/sh
cd "`dirname $0`"
. ./mpconfig
#xterm -fn -misc-fixed-medium-r-normal--18-120-100-100-c-90-iso10646-1 -e ./mpopt
xterm -fn -misc-fixed-medium-r-normal--20-200-75-75-c-100-iso10646-1 -e ./mpopt
