(*
 *
 * ----------------------------------------------------------------
 *
 * @begin[license]
 * Copyright (C) 2004 Mojave Group, Caltech
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 * Author: Jason Hickey
 * @email{jyh@cs.caltech.edu}
 * @end[license]
 *)
extends Mptop

open Opname
open Refiner.Refiner
open Refiner.Refiner.TermType
open Tactic_type.Tactic

open Shell_sig

(*
 * Update the commands.
 *)
val synchronize : (shell_commands -> unit) -> unit

(*
 * Name from an opname.
 *)
val mk_dep_name : opname -> string

(* Quit *)
topval exit : unit -> unit
topval abort : unit -> unit

(* Proof navigation. *)
topval cd : string -> string
topval refresh : unit -> unit
topval pwd : unit -> string
topval relative_pwd : unit -> string
topval fs_pwd : unit -> string
topval root : unit -> string
topval up : int -> unit
topval down : int -> unit

(* Proof editing *)
topval refine : tactic -> unit
topval expand : unit -> unit
topval expand_all : unit -> unit
topval kreitz : unit -> unit
topval clean : unit -> unit
topval clean_all : unit -> unit
topval squash : unit -> unit
topval squash_all : unit -> unit
topval undo : unit -> unit
topval redo : unit -> unit
topval copy : string -> unit
topval paste : string -> unit
topval make_assum : unit -> unit
topval check : unit -> unit
topval check_all : unit -> unit
topval status_all : unit -> unit
topval find_subgoal : int -> string

(* Module commands. *)
topval create_pkg : string -> unit
topval backup : unit -> unit
topval backup_all : unit -> unit
topval save : unit -> unit
topval save_all : unit -> unit
topval export : unit -> unit
topval export_all : unit -> unit
topval revert : unit -> unit
topval revert_all : unit -> unit

(* Display *)
topval ls : string -> unit
topval set_dfmode : string -> unit
topval set_tex_file : string -> unit
topval print_theory : string -> unit

(* View options *)
topval get_view_options : unit -> string
topval set_view_options : string -> unit
topval clear_view_options : string -> unit

(* Other utilities *)
topval create_ax_statement : term -> string -> unit
topval set_debug : string -> bool -> unit
topval stop_gmon : unit -> unit
topval restart_gmon : unit -> unit
topval print_gc_stats : unit -> unit

(* Callback to return a primitive proof. Filter passes this to Refine module *)
val extract : string list -> unit -> Refine.extract

(*
 * Extraction of the constructive contents.
 * This is a temporary API, until a better one is implemented
 * (the input term list * should be generated by the refiner as well!)
 *)
topval term_of_extract : term list -> term

(*
 * Init function is called by toploop.
 *)
val init : unit -> unit

(*
 * Test whether a method is enabled.
 *)
val is_enabled : method_name -> bool

(*
 * Edit a file.
 *)
val edit : string -> unit

(*!
 * @docoff
 *
 * -*-
 * Local Variables:
 * Caml-master: "compile"
 * End:
 * -*-
 *)
