#!/bin/sh

#
# Run this script to compare the proofs status in your current tree
# to the one in the clean tree in the last successful nightly run.
#
# For best results, use THEORIES=all and TESTS_ENABLED=yes (since this is what
# the nightly run uses).
#

FOREGR=""

if [ ! -d editor/ml ]; then
   echo "Should be ran from MetaPrl root"
   exit 1
fi
if [ ! -f mk/config ]; then
   echo "You need a valid mk/config"
   exit 1
fi
if [ "$1" = "foregr" ]; then
   FOREGR="yes"
   shift
fi
if grep -qi '^THEORIES *= *ALL$' mk/config ; then :; else
   echo "Warning: to make the comparison more adequate, use THEORIES=all in mk/config"
fi
if grep -E -qi '^TESTS_ENABLED *= *(YES|true) *$' mk/config ; then :; else
   echo "Warning: to make the comparison more adequate, use TESTS_ENABLED=true in mk/config"
fi
# SSH="ssh -x -n -o BatchMode=yes `whoami`@localhost `pwd`/util/check-status.sh `pwd` update"
SSH="`pwd`/util/check-status.sh `pwd` update"
if [ "$MP_DEBUG" ]; then
   SSH=$SSH MP_DEBUG "$MP_DEBUG"
fi
if [ "$FOREGR" ]; then
   $SSH "$@" < /dev/null
else
   $SSH "$@" < /dev/null &
   date "+%c: check-status.sh spawned, results should be emailed to you in a little while"
fi
