#!/bin/sh
OUT=`mktemp /tmp/clean-opens.XXXXXX`
YES=0
NO=0
unset OMAKEFLAGS
(
omake clean
cvs update
IFS=::::::
TMP=`mktemp /tmp/clop.XXXXXX`
TMP2=`mktemp /tmp/clop2.XXXXXX`
TMP3=`mktemp /tmp/clop3.XXXXXX`
grep -r -l --include=\*.ml --include=\*.mli --include=\*.mlz --include=\*.mll --include=\*.mly '^ *open ' . > $TMP
omake || exit 1
while read FILE; do
   BINFILE=`echo $FILE|sed -e 's/\.mli$/.cmi/' -e 's/\.mlz$/.cmi/' -e 's/\.ml.*$/.cmo/'`
   if [ "$BINFILE" == "$FILE" ]; then
      echo "$FILE" "???"
      exit 1
   fi
   if [ ! -e "$BINFILE" ]; then
      echo "Skiping file $FILE as it is not compiled by \"omake\""
   else
      if echo "$BINFILE" | grep -q cmo; then
         PPO=`echo $BINFILE|sed -e 's/\.cmo$/.ppo/'`
      else
         PPO=""
      fi
      grep '^ *open ' $FILE > $TMP2
      while read OPEN; do
         echo -n "Trying to remove \"$OPEN\" from $FILE: "
         mv -f "$FILE" "$FILE.save"
         fgrep -v -x "$OPEN" $FILE.save > $FILE
         if cmp -s $FILE $FILE.save; then
            echo "Warning: grep -v did not remove anything"
            rm -f $FILE.save
         else
            rm -f $BINFILE $PPO
            if omake "$BINFILE" 2>&1 >/dev/null && [ -f $BINFILE ]; then
               echo success!
               YES=$[$YES + 1]
               rm -f $FILE.save
            else
               echo failed.
               NO=$[$NO + 1]
               mv -f $FILE.save $FILE
               touch $FILE
               rm -f "$BINFILE" "$PPO"
            fi
         fi
      done < $TMP2
   fi
done < $TMP
echo "Removed $YES out of $[$YES + $NO]" > $TMP3
rm -f $TMP $TMP2
) > $OUT
if [ -z "$LOGNAME" ]; then
   LOGNAME=`whoami`
fi
(
   cat $TMP3
   rm -f $TPM3
   echo " "
   echo "The full log is in $OUT on `hostname -s`; ends with"
   echo ...
   tail $OUT
   echo "---"
) | mail "$LOGNAME" -s "Cleaning opens in `pwd` done."
