#!/usr/bin/perl -w

if ($#ARGV != 0) {
    die "Usage: gen_refiner_debug.pl Modname < interface";
};

$modname = shift;

$line = "";

$merges{"operator"}="merge_op";
$merges{"operator'"}="merge_op'";
$merges{"bound_term"}="merge_bterm";
$merges{"bound_term'"}="merge_bterm'";
foreach my $ty ("bool", "unit", "param", "term", "var", "int", "level_exp", "level_exp_var", "opname", "string") {
    $merges{$ty}="merge_$ty";
    $merges{"$ty list"}="merge_" . $ty . "s";
};
foreach my $ty ("term", "param", "level_exp", "level_exp_var") {
    my $ty2 = $ty . "'";
    $merges{$ty2} = "merge_$ty2";
    $merges{"$ty2 list"} = "merge_$ty" . "s'";
}
$merges{"Lm_num.num"} = "merge_num";

foreach my $ty ("bool", "int", "var", "opname", "out_channel", "string", "Lm_num.num") {
    $splits{$ty} = $splits{"$ty list"}="";
};
foreach my $ty ("term", "bound_term", "param", "operator", "level_exp", "level_exp_var") {
    $splits{$ty} = "identity";
    $splits{"$ty list"} = "split";
};
foreach my $ty ("term", "param", "level_exp", "level_exp_var") {
    my $ty = $ty . "'";
    $splits{$ty} = "split_$ty";
}
$splits{"bound_term'"} = "split_bterm'";
$splits{"operator'"} = "split_op'";

$merges{"object_id"} = $merges{"param list"};
$splits{"object_id"} = $splits{"param list"};

sub do_split($$) {
    my ($type, $arg) = @_;
    if (not(defined $splits{$type})) { die "\n\nDo not know how to split $type" };
    my $split = $splits{$type};
    if ($split eq "") {
	return ($arg, $arg);
    } else {
	$arg1 = $arg . "_1";
	$arg2 = $arg . "_2";
	print "         let $arg1, $arg2 =";
	if ($split ne "identity") { print " $split" };
	print " $arg in\n";
	return ($arg1, $arg2);
    }
}

sub process ($) {
    my ($fullline) = ($line) = @_;
    my $args1="";
    my $args2="";
    $line=~s/^[[:space:]]*//;
    $line=~s/[[:space:]]*$//;
    if (not($line =~/^val[[:space:]]/)) { return () };
    $line=~s/^val[[:space:]]*//;
    if ($line=~/\bval\b/) {
	die "\n\nLine has more than one \"val\" on it: $fullline"
    };
    if ($line=~/:.*:/) {
	die "\n\nLine has to many \":\" symbols: $fullline"
    }
    if (not($line=~/:/)) {
	die "\n\nLine has no \":\" on it: $fullline"
    };
    $line=~s/[[:space:]]+/ /g;
    my ($name, $rest) = split(/[[:space:]]*:[[:space:]]*/, $line);
    my @types = split(/[[:space:]]*->[[:space:]]*/, $rest);
    my $tyres = pop(@types);
    print "      let $name ";
    for (my $i=0; $i<=$#types; $i++) { print "(p$i : $types[$i]) " };
    print "=\n";
    for (my $i=0; $i<=$#types; $i++) {
	my ($arg1, $arg2) = do_split($types[$i], "p$i");
	$args1 .= " $arg1";
	$args2 .= " $arg2";
    }
    if (defined $merges{$tyres}) {
	print "         ", $merges{$tyres}, " \"$modname.$name\" (" , $modname, "1.$name$args1) (", $modname, "2.$name$args2)\n\n";
    } else {
	if ($tyres =~ /^\([^()]*\)$/) { $tyres =~ s/[()]//g };
	if ($tyres =~ /\*/) {
	    my @tyress = split(/[[:space:]]*\*[[:space:]]*/,$tyres);
	    my $let1 = $let2 = "         let ";
	    for (my $i=0; $i<=$#tyress; $i++) {
		if ($i > 0) {
		    $let1 .= ", ";
		    $let2 .= ", ";
		}
		$let1 .= "res$i" . "_1";
		$let2 .= "res$i" . "_2";
	    }
	    print $let1, " = " , $modname, "1.$name$args1 in\n";
	    print $let2, " = " , $modname, "2.$name$args2 in\n";
	    for (my $i=0; $i<=$#tyress; $i++) {
		if (defined $merges{$tyress[$i]}) {
		    print "         (", $merges{$tyress[$i]}, " \"$modname.$name - $i\" res$i", "_1 res$i", "_2)", (($i<$#tyress)?",":"\n"), "\n";
		} else { die "\n\nDo not know how to merge $tyress[$i]" }
	    }
	} else { die "\n\nDo not know how to merge $tyres" }
    }
}

print "      (* The rest of this module is auto-generated by the util/gen_refiner_debug.pl script *)\n\n";

while (<>) {
    if (/\(\*/ || /\*\)/) {
	die "\n\nComments on input not supported!"
    };
    if (/\btype\b/) {
	die "\n\nTypes on input not supported!"
    };
    if (/\bval\b/) {
	process($line);
	$line=$_
    } else {
	$line .= " ";
	$line .= $_;
    }
}
process($line);


