(*
 * These are all the errors that are generated by any module
 * in the refiner.
 *
 * ----------------------------------------------------------------
 *
 * This file is part of MetaPRL, a modular, higher order
 * logical framework that provides a logical programming
 * environment for OCaml and other languages.
 *
 * See the file doc/index.html for information on Nuprl,
 * OCaml, and more information about this system.
 *
 * Copyright (C) 1998 Jason Hickey, Cornell University
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 * Author: Jason Hickey
 * jyh@cs.cornell.edu
 *)

(*
 * We use this module to express sharing constraints.
 *)
module type TypeSig =
sig
   type t
end

(*
 * Error module.
 *)
module type RefineErrorSig =
sig
   (*
    * Regular term parts.
    *)
   type level_exp
   type param
   type term
   type bound_term

   (*
    * Types over terms.
    *)
   type meta_term
   type address
   type seq_hyps
   type seq_goals

   (*
    * Match errors in the rewriter.
    *)
   type match_type =
      ParamMatch of param
    | VarMatch of string
    | TermMatch of term
    | BTermMatch of bound_term
    | HypMatch of seq_hyps
    | GoalMatch of seq_goals

   (*
    * We declare the general exception type for all the
    * modules in the refiner.
    *
    * GenericError is used when the specific error is not desired.
    *)
   type refine_error =
      (* Generic error is used in simplified refiners *)
      GenericError

      (* Mptop toploop ignore this error *)
    | ToploopIgnoreError

      (* General refinement errors *)
    | StringError of string
    | IntError of int
    | TermError of term
    | StringIntError of string * int
    | StringStringError of string * string
    | StringTermError of string * term
    | GoalError of string * refine_error
    | SecondError of string * refine_error
    | SubgoalError of int * string * refine_error
    | PairError of string * refine_error * string * refine_error

      (* Addressing errors *)
    | NodeError of string * term * (string * refine_error) list
    | AddressError of address * term

      (* Term module errors *)
    | TermMatchError of term * string
    | TermPairMatchError of term * term
    | MetaTermMatchError of meta_term

      (* Rewriter errors *)
    | RewriteBoundSOVar of string
    | RewriteFreeSOVar of string
    | RewriteSOVarArity of string
    | RewriteBoundParamVar of string
    | RewriteFreeParamVar of string
    | RewriteBadRedexParam of param
    | RewriteNoRuleOperator
    | RewriteBadMatch of match_type
    | RewriteAllSOInstances of string
    | RewriteMissingContextArg of string
    | RewriteStringError of string
    | RewriteAddressError of address * string * refine_error
    | RewriteFreeContextVars of string list

   (*
    * Every error is paired with the name of
    * the function that raised it.
    *)
   exception RefineError of string * refine_error

   (*
    * A default exception.
    *)
   val generic_refiner_exn : exn
end
