type token =
    TokEof
  | TokAt of (Phobos_type.pos)
  | TokEq of (Phobos_type.pos)
  | TokRuleEq of (Phobos_type.pos)
  | TokArrow of (Phobos_type.pos)
  | TokDoubledArrow of (Phobos_type.pos)
  | TokPipe of (Phobos_type.pos)
  | TokSemi of (Phobos_type.pos)
  | TokColon of (Phobos_type.pos)
  | TokComma of (Phobos_type.pos)
  | TokLeftBrace of (Phobos_type.pos)
  | TokRightBrace of (Phobos_type.pos)
  | TokLeftBrack of (Phobos_type.pos)
  | TokRightBrack of (Phobos_type.pos)
  | TokIgnore of (Phobos_type.pos)
  | TokBang of (Phobos_type.pos)
  | TokDot of (Phobos_type.pos)
  | TokQuestionMark of (Phobos_type.pos)
  | TokLe of (Phobos_type.pos)
  | TokGe of (Phobos_type.pos)
  | TokStart of (Phobos_type.pos)
  | TokLongest of (Phobos_type.pos)
  | TokFirst of (Phobos_type.pos)
  | TokExtend of (Phobos_type.pos)
  | TokRemove of (Phobos_type.pos)
  | TokOverride of (Phobos_type.pos)
  | TokNonAssoc of (Phobos_type.pos)
  | TokLeftAssoc of (Phobos_type.pos)
  | TokRightAssoc of (Phobos_type.pos)
  | TokPrec of (Phobos_type.pos)
  | TokModule of (Phobos_type.pos)
  | TokInclude of (Phobos_type.pos)
  | TokTerms of (Phobos_type.pos)
  | TokTokens of (Phobos_type.pos)
  | TokGrammar of (Phobos_type.pos)
  | TokDeclare of (Phobos_type.pos)
  | TokRewrites of (Phobos_type.pos)
  | TokInline of (Phobos_type.pos)
  | TokOption of (string * Phobos_type.pos)
  | TokString of (string * Phobos_type.pos)
  | TokInt of (int * Phobos_type.pos)
  | TokFloat of (float * Phobos_type.pos)
  | TokId of (string * Phobos_type.pos)
  | TokQuotedId of (string * Phobos_type.pos)

val main :
  (Lexing.lexbuf  -> token) -> Lexing.lexbuf -> Phobos_type.phobos_parser_return_type
