#!/bin/sh

MP_CWD=`pwd`
export MP_CWD

cd `dirname "$0"`

if [ ! -x mp.top ]; then
    echo "The bytecode binary mp.top does not exist or is not executable."
    echo "Did you mean to run the native code binary `dirname "$0"`/mpopt instead?"
    exit 1
fi

#
# Configuration
#
. ./mpconfig

#
# Start the executable.
#
exec ./mp.top $INCLUDES "$@"
